apiVersion: v1
kind: Service
metadata:
  name: diary-app
  labels:
    app: diary
spec:
  selector:
    app: diary
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 35.205.142.78